---
version: 1.0.0
name: OpenStreetMap 台灣
description: 廣泛運用的圖資 自由開放的圖資
url: https://osm.tw/
baseurl: /
repository: https://github.com/OsmHackTW/osmtw-ghpage/
timezone: Asia/Taipei
logo: "/assets/img/logo.png"
ico: "/assets/img/icon.ico"
google_analytics_id: UA-136100516-1
# google_site_verification: 

sass:
  sass_dir: _sass
  style: compressed

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-github-metadata

exclude:
  - .gitignore
  - .jekyll-cache
  - CNAME
  - icomoon-selection.json
  - readme.md