name: ci

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    env:
      NODE_ENV: production

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      - name: Cache  💾
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install and Build 🔧
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn ci
          yarn build
          yarn export
          touch ./out/.nojekyll
        env:
          CI: true
          NODE_ENV: production

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
